name: echo_sys_info

on: 
  workflow_dispatch:


jobs:

  macos_info:
    name: macos-xcode-info
    runs-on: macos-11
    steps:
    - name: Run script
      run: |
        xcodebuild -version -sdk
        xcrun --sdk iphoneos --show-sdk-path
        
  macos_setup_xcode:
    name: xcode-setup-xcode
    runs-on: macos-11
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '11'
    - name: Run script
      run: |
        xcodebuild -version -sdk
        xcrun --sdk iphoneos --show-sdk-path
        
  macos_setup_xcode2:
    name: xcode-setup-xcode2
    runs-on: macos-11
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '12.4.0'
    - name: Run script
      run: |
        xcodebuild -version -sdk
        xcrun --sdk iphoneos --show-sdk-path
        
